name: Update README with Latest Blog Posts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Pull latest blog posts into README

    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://waynegoosen.com/index.xml"
          max_post_count: 5
          comment_tag_name: "BLOG-POST-LIST"
